# Generated by Django 4.2.5 on 2023-09-30 18:15

from django.db import migrations, models
import django.utils.timezone
import shops.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shops.models.user_directory_path,
                    ),
                ),
                ("excerpt", models.TextField(null=True)),
                ("content", models.TextField()),
                (
                    "slug",
                    models.SlugField(
                        max_length=500, unique=True, unique_for_date="published"
                    ),
                ),
                ("published", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
