# Generated by Django 4.2.5 on 2023-09-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="excerpt",
        ),
        migrations.RemoveField(
            model_name="post",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog"),
        ),
    ]
