# Generated by Django 4.2.5 on 2023-09-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0002_remove_post_content_remove_post_excerpt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
