# Generated by Django 4.2.5 on 2023-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0003_post_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="title",
            new_name="direccion",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="image",
            new_name="imagen",
        ),
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.AddField(
            model_name="post",
            name="ciudad",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="latitud",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="longitud",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="nombre",
            field=models.CharField(default="sin registro", max_length=300),
        ),
        migrations.AddField(
            model_name="post",
            name="puntuacion",
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name="post",
            name="telefono",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="web",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                max_length=550, unique=True, unique_for_date="published"
            ),
        ),
    ]
