# Generated by Django 4.1.4 on 2023-10-09 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0004_rename_title_post_direccion_rename_image_post_imagen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_cat", models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_city", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shops.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="ciudad",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="shops.city"
            ),
        ),
    ]
