# Generated by Django 4.1.4 on 2023-10-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0005_category_city_post_categoria_alter_post_ciudad"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ciudad_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="shops.city"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="ciudad",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
